language: python
python:
  - '3.6'
notifications:
  email: true
before_install:
  - export PATH="./.travis:$HOME/miniconda/bin:$PATH"
  - sudo apt-get -qq update
  - bash .travis/install_conda.sh
install: "pip install --quiet -r requirements.txt"
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
script: make travis
after_script:
  - echo "Rendered notebook http://nbviewer.jupyter.org/urls/s3.amazonaws.com/pythonplotbuilds/tdhopper/pythonplot.com/$TRAVIS_BUILD_NUMBER/$TRAVIS_JOB_NUMBER/Examples.$(git log -1 --pretty=format:'%h').ipynb"
before_deploy:
  - npm install netlify-cli -g
deploy:
  provider: script
  script: ./netlify_deploy.sh
  skip_cleanup: true
  on:
    all_branches: true
addons:
  artifacts: true
