dist: xenial
addons:
  artifacts: true
  apt:
    packages:
    - firefox-geckodriver
language: python
python:
  - '3.7'
notifications:
  email: true
install:
  - sudo add-apt-repository --yes ppa:marutter/rrutter3.5
  - sudo apt-get update --yes
  - sudo apt install r-api-3.5 --yes
  - mkdir orca
  - wget --quiet https://github.com/plotly/orca/releases/download/v1.2.1/orca-1.2.1-x86_64.AppImage -O ./orca/orca
  - chmod +x orca.AppImage 
  - export PATH="${HOME}/orca:${PATH}"
  - pip install --quiet -r requirements.txt
before_script:
  - orca --help
  - pip freeze
services:
  - xvfb
script: make travis
before_deploy:
  - npm install netlify-cli -g
deploy:
  provider: script
  script: ./netlify_deploy.sh
  skip_cleanup: true
  on:
    all_branches: true