language: python
python:
  - '3.7'
notifications:
  email: true
before_install:
  - R --version
install:
  - wget --quiet https://github.com/plotly/orca/releases/download/v1.2.1/orca-1.2.1-x86_64.AppImage -O orca.AppImage
  - chmod +x orca.AppImage 
  - pip install --quiet -r requirements.txt
after_install:
  - pip freeze  
dist: xenial
services:
  - xvfb
script: make travis
before_deploy:
  - npm install netlify-cli -g
deploy:
  provider: script
  script: ./netlify_deploy.sh
  skip_cleanup: true
  on:
    all_branches: true
addons:
  artifacts: true
  apt:
    sources:
    - r-packages-precise
    packages:
    - firefox-geckodriver
    - r-base
